# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0489b1eaec7de584364cc22365d05d6d8df67ffabac74e43c984bddea1846a60f95d04f629e2010e23ad8269c42d959f617668894e251c5f9b466d40d3fd4236
  google_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyA-xSDLEY9Bzu0kRSeADDY5ssZySqfIYMw") %>
  wunderground_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "874c67955bc9392d") %>
  amdoren_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "mLN6buyzmFbcmLWabTHrTEYewk5V6G") %>
  openweathermap_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "a91cea30c76e3ecc9e43dde26f7857b4") %>
  # twilio_sid: <%= ENV.fetch("TWILIO_SID", "ACaa68a3ced228921b59814e6899a96312") %>
  # twilio_token: <%= ENV.fetch("TWILIO_TOKEN", "172ff4e6a210c51338ca400d89e4bd3f") %>
  # twilio_phone: <%= ENV.fetch("TWILIO_PHONE", "+12244791908") %>
  # admin_phone: <%= ENV.fetch("ADMIN_PHONE", "+18473440289") %>

test:
  secret_key_base: 9a6ca12cbce71fd7f596c89f5a4d0d545e70c2f12ab5fdccb227a128fa8a1a6bb0860f5bac52af0f25b12f2cd5fc0ac89eb95ae11394eb6ae66766725554a350
  google_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyA-xSDLEY9Bzu0kRSeADDY5ssZySqfIYMw") %>
  wunderground_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "874c67955bc9392d") %>
  amdoren_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "mLN6buyzmFbcmLWabTHrTEYewk5V6G") %>
  openweathermap_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "a91cea30c76e3ecc9e43dde26f7857b4") %>
  # twilio_sid: <%= ENV.fetch("TWILIO_SID", "ACe5ad25bfc3c440ec67d5c91c00730f69") %>
  # twilio_token: <%= ENV.fetch("TWILIO_TOKEN", "2d09a014fb3eef322df69c7b524727f6") %>
  # twilio_phone: <%= ENV.fetch("TWILIO_PHONE", "+15005550006") %>
  # admin_phone: <%= ENV.fetch("ADMIN_PHONE", "+8152286924") %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "set-a-value-in-secrets-yml") %>
  wunderground_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "set-a-value-in-secrets-yml") %>
  amdoren_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "set-a-value-in-secrets-yml") %>
  openweathermap_api_key: <%= ENV.fetch("SECRET_KEY_BASE", "set-a-value-in-secrets-yml") %>
  # twilio_sid: <%= ENV.fetch("TWILIO_SID", "set-a-value-in-secrets-yml") %>
  # twilio_token: <%= ENV.fetch("TWILIO_TOKEN", "set-a-value-in-secrets-yml") %>
  # twilio_phone: <%= ENV.fetch("TWILIO_PHONE", "set-a-value-in-secrets-yml") %>
  # admin_phone: <%= ENV.fetch("ADMIN_PHONE", "+8152286924") %>
